export const RESIZE_WIDGET = 'RESIZE_WIDGET';
export const ADD_WIDGET = 'ADD_WIDGET';
export const CHANGE_WIDGET = 'CHANGE_WIDGET';
export const CHANGE_WIDGET_TITLE = 'CHANGE_WIDGET_TITLE';
export const CHANGE_WIDGET_DATA = 'CHANGE_WIDGET_DATA';
export const LOAD_WIDGETS = 'LOAD_WIDGETS';
